ALTER TABLE applicationversions ADD COLUMN IF NOT EXISTS apkhash VARCHAR(100);
ALTER TABLE configurationapplications ADD COLUMN IF NOT EXISTS remove BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE configurationapplications ADD COLUMN IF NOT EXISTS longtap BOOLEAN NOT NULL DEFAULT FALSE;
