-- Settings columns used by React settings UI (subset of Java Settings).

ALTER TABLE settings ADD COLUMN IF NOT EXISTS language VARCHAR(20) DEFAULT 'en';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS usedefaultlanguage BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS createnewdevices BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS newdeviceconfigurationid INT;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS passwordlength INT NOT NULL DEFAULT 6;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS passwordstrength INT NOT NULL DEFAULT 0;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS backgroundcolor VARCHAR(20) DEFAULT '#678ca6';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS textcolor VARCHAR(20) DEFAULT '#ffffff';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS backgroundimageurl VARCHAR(500);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS iconsize VARCHAR(20) DEFAULT 'SMALL';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS desktopheader VARCHAR(20) DEFAULT 'NO_HEADER';
